# Generated by Django 5.2.4 on 2025-08-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0002_alter_genre_type_alter_movie_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Saytga chiqarish vaqti'),
        ),
    ]
