# Generated by Django 5.2.5 on 2025-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0004_alter_movie_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='movie',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Saytga chiqarish?'),
        ),
    ]
