# Generated by Django 5.2.5 on 2025-09-12 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0007_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['job'], 'permissions': [('can_add_movie', 'Can add movie'), ('can_update_movie', 'Can update movie'), ('can_delete_movie', 'Can delete movie')], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
    ]
