# Generated by Django 5.2.5 on 2025-09-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviesite', '0008_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['job'], 'permissions': [('can_view_all_profiles', "Barcha profillarni ko'rish imkoni"), ('can_edit_own_profile', "O'z profilini tahrirlash imkoni"), ('can_delete_own_profile', "O'z profilini o'chirish imkoni")], 'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
    ]
